name: Publish Linux Docker Images

on:
  workflow_dispatch:
    inputs:
      docker_image_tag:
        description: 'Docker Image Tag (yyyyMMdd)'
        required: true

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  validate_inputs:
    runs-on: ubuntu-latest
    steps:
      - name: validate input
        run: |
          if [[ ! ${{ github.event.inputs.docker_image_tag }} =~ ^[0-9]{8}$ ]]; then
            echo "::error Invalid tag name '${{ github.event.inputs.docker_image_tag }}'"
            exit 1
          fi

  publish:
    strategy:
      matrix:
        os: 
          - ubuntu22
        base_name: 
          - dotnet8
          - dotnet8sdk
        opencv_version: 
          - '4.9.0'

    env:
      IMAGE_NAME: ${{ matrix.os }}-${{ matrix.base_name }}-opencv${{ matrix.opencv_version }}
      IMAGE_TAG: ${{ github.event.inputs.docker_image_tag }}

    runs-on: ubuntu-latest

      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: docker build
        run: |
          docker build -f "docker/${IMAGE_NAME}/Dockerfile -t "ghcr.io/${GITHUB_REPOSITORY}/${IMAGE_NAME}:${IMAGE_TAG}" .

      - name: docker login
        run: |
          echo ${{secrets.GH_PACKAGES_PAT}} | docker login ghcr.io -u "${GITHUB_REPOSITORY_OWNER}" --password-stdin

      - name: docker push
        run: |
          docker push "ghcr.io/${GITHUB_REPOSITORY}/${IMAGE_NAME}:${IMAGE_TAG}"
